### ISSUE TITLE
项目无法构建+QQ群的疑问

### ISSUE THREAD

**Issue by xiaoCong2014** [fuhoujun/jee_framework#1]
构建须知里，“项目默认用到80端口，请检查80端口是否被占用”，我win10的这个端口被系统进程占用了，怎么修改项目的默认端口？（这个系统进程不好关闭）还有，默认端口别用80吧，很多软件的默认端口都是80，比如迅雷。

**Comment by fuhoujun** [comment]
QQ 群：540553957

可修改此文件
e/e-example/e-example-single/src/main/resources/application.yml

server:
  port: 80
  tomcat:
    uri-encoding: UTF-8
